/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

Runtime: 8 ms, faster than 25.50% of Java online submissions
*/

class Solution {
    public char findTheDifference(String s, String t) {
        char sArray[] = s.toCharArray(); 
        char tArray[] = t.toCharArray();
        Arrays.sort(sArray);
        Arrays.sort(tArray); 
        for(int i = 0; i < tArray.length; i ++) {
            if(i == tArray.length - 1) return tArray[i];
            else if(sArray[i] != tArray[i]) return tArray[i];
        }
        return '-';
    }
}